# Generated by Django 2.2.3 on 2019-07-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='idno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
